##\
# This file is a part of the phpMussel\FrontEnd package.
# Homepage: https://phpmussel.github.io/
#
# PHPMUSSEL COPYRIGHT 2013 AND BEYOND BY THE PHPMUSSEL TEAM.
#
# License: GNU/GPLv2
# @see LICENSE.txt
#
# This file: Configuration defaults file (last modified: 2020.12.04).
##/

frontend:
 frontend_log:
  type: "string"
  default: ""
 max_login_attempts:
  type: "int"
  default: 5
 numbers:
  type: "string"
  default: "Latin-1"
  choices:
   NoSep-1: "1234567.89"
   NoSep-2: "1234567,89"
   Latin-1: "1,234,567.89"
   Latin-2: "1â€¯234â€¯567.89"
   Latin-3: "1.234.567,89"
   Latin-4: "1â€¯234â€¯567,89"
   Latin-5: "1,234,567Â·89"
   Arabic-1: "Ù¡Ù¢Ù£Ù¤Ù¥Ù¦Ù§Ù«Ù¨Ù©"
   Arabic-2: "Ù¡Ù¬Ù¢Ù£Ù¤Ù¬Ù¥Ù¦Ù§Ù«Ù¨Ù©"
   Arabic-3: "Û±Ù¬Û²Û³Û´Ù¬ÛµÛ¶Û·Ù«Û¸Û¹"
   Arabic-4: "Û±Û²Ù¬Û³Û´Ù¬ÛµÛ¶Û·Ù«Û¸Û¹"
   Base-12: "4b6547.a8"
   Base-16: "12d687.e3"
   Bengali-1: "à§§à§¨,à§©à§ª,à§«à§¬à§­.à§®à§¯"
   Burmese-1: "áá‚áƒá„á…á†á‡.áˆá‰"
   China-1: "123,4567.89"
   India-1: "12,34,567.89"
   India-2: "à¥§à¥¨,à¥©à¥ª,à¥«à¥¬à¥­.à¥®à¥¯"
   India-3: "à«§à«¨,à«©à«ª,à««à«¬à«­.à«®à«¯"
   India-4: "à©§à©¨,à©©à©ª,à©«à©¬à©­.à©®à©¯"
   India-5: "à³§à³¨,à³©à³ª,à³«à³¬à³­.à³®à³¯"
   India-6: "à±§à±¨,à±©à±ª,à±«à±¬à±­.à±®à±¯"
   Japanese: "ç™¾ä¸‡äºŒåä¸‡ä¸‰ä¸‡å››åƒäº”ç™¾å…­åä¸ƒãƒ»å…«ä¹åˆ†"
   Javanese: "ê§‘ê§’ê§“ê§”ê§•ê§–ê§—.ê§˜ê§™"
   Khmer-1: "áŸ¡.áŸ¢áŸ£áŸ¤.áŸ¥áŸ¦áŸ§,áŸ¨áŸ©"
   Lao-1: "à»‘à»’à»“à»”à»•à»–à»—.à»˜à»™"
   Mayan: "ð‹§ð‹®ð‹¦ð‹¨ð‹§.ð‹±ð‹°"
   Mongolian: "á ‘á ’á “á ”á •á –á —.á ˜á ™"
   Odia: "à­§à­¨à­©à­ªà­«à­¬à­­.à­®à­¯"
   Thai-1: "à¹‘,à¹’à¹“à¹”,à¹•à¹–à¹—.à¹˜à¹™"
   Thai-2: "à¹‘à¹’à¹“à¹”à¹•à¹–à¹—.à¹˜à¹™"
   Tibetan: "à¼¡à¼¢à¼£à¼¤à¼¥à¼¦à¼§.à¼¨à¼©"
 default_algo:
  type: "string"
  default: "PASSWORD_DEFAULT"
  choices:
   PASSWORD_DEFAULT: "PASSWORD_DEFAULT"
   PASSWORD_BCRYPT: "PASSWORD_BCRYPT"
   PASSWORD_ARGON2I: "PASSWORD_ARGON2I (PHP >= 7.2.0)"
   PASSWORD_ARGON2ID: "PASSWORD_ARGON2ID (PHP >= 7.3.0)"
  choice_filter: "filterByDefined"
 theme:
  type: "string"
  default: "default"
  preview: "allow_other"
  allow_other: true
  choices:
   default: "Default"
   bluemetal: "Blue Metal"
   fullmoon: "Full Moon"
   moss: "Moss"
   primer: "Primer"
   primerdark: "Primer Dark"
   rbi: "Red-Blue Inverted"
   slate: "Slate"
 magnification:
  type: "float"
  step: "any"
  default: 1
